services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - taskdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://taskdb:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret

  taskdb:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskdb

volumes:
  taskdb_data:
